// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/goki0524/clean-arch/infrastructure"
	"github.com/goki0524/clean-arch/infrastructure/repository"
	"github.com/goki0524/clean-arch/presentation/controllers"
	"github.com/goki0524/clean-arch/usecases"
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
	"github.com/labstack/echo"
)

// Injectors from wire.go:

// Initialize DI
func Initialize(e *echo.Echo, db *gorm.DB) *infrastructure.Router {
	companyBedRepository := repository.NewCompanyBedRepository(db)
	usersUseCase := usecases.NewUsersUseCase(companyBedRepository)
	usersController := controllers.NewUsersController(usersUseCase)
	router := infrastructure.NewRouter(e, usersController)
	return router
}

// wire.go:

var set = wire.NewSet(infrastructure.NewRouter, controllers.NewUsersController, repository.NewCompanyBedRepository, wire.Bind(new(repository.ICompanyBedRepository), new(*repository.CompanyBedRepository)), usecases.NewUsersUseCase, wire.Bind(new(usecases.IUsersUseCase), new(*usecases.UsersUseCase)))
